#!/bin/bash

# TODO: background rackup first, then launch browser. Kill rackup on finish.

clear

echo -e "NOTE: launches browser first, so need to reload page once server is running"

CMD="open http://localhost:9292"
echo -e "$HOSTNAME\$ $CMD\n"
$CMD

CMD="rackup"
echo -e "$HOSTNAME\$ $CMD\n"
$CMD

